# WordPress MCP Server Configuration
# Configure your WordPress sites and general settings

settings:
  default_post_status: "draft"    # draft, publish, private
  default_post_format: "standard"
  max_retries: 3
  timeout: 30

sites:
  - id: "site1"
    name: "rox"
    url: "https://www.rox.co.il"
    username: "shay@smgroup.co.il"
    password: "WCnr AqtL ra0E xxeh b7mm ydt9"  # WordPress Application Password
    
  - id: "site2"
    name: "Second Site"
    url: "https://example2.com"
    username: "your-username"
    password: "your-app-password"
    
  # Add your additional sites here (up to 70 total)
  # Format:
  # - id: "siteX"
  #   name: "Site Display Name"
  #   url: "https://your-site-X.com"
  #   username: "your-username"
  #   password: "your-app-password"

# Notes:
# - Use WordPress Application Passwords, not regular user passwords
# - Each site needs a unique ID
# - The API URL is automatically constructed from the site URL
# - Supports both Hebrew and English content creation 
